version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  # Expose Ollama API on port 11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
      - ./start-ollama.sh:/start-ollama.sh:ro
    container_name: ollama
    restart: always
    networks:
      - ollama-docker
    healthcheck:
      test: ["CMD", "pgrep", "-f", "ollama"]
      interval: 30s
      retries: 10
      start_period: 120s
      timeout: 10s
    command: ["sh", "-c", "/start-ollama.sh && ollama serve"]
    
  fastapi:
    build:
      context: .  # Set build context to the repository root
      dockerfile: api/Dockerfile  # Specify the Dockerfile location relative to the context
    container_name: fastapi
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    depends_on:
      - ollama  # Ensure Ollama is running before FastAPI starts
    networks:
      - ollama-docker
    environment:
      - OLLAMA_API_URL=http://ollama:11434/  # Use correct API URL

networks:
  ollama-docker:
    driver: bridge  # Ensures both containers communicate properly
