version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"  # Expose Ollama API on port 11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    restart: always
    networks:
      - ollama-docker
    healthcheck:
      test: ["CMD", "pgrep", "-f", "ollama"]
      interval: 30s
      retries: 10
      start_period: 120s
      timeout: 10s

  fastapi:
    build:
      context: .  # Set build context to the repository root
      dockerfile: api/Dockerfile  # Specify the Dockerfile location relative to the context
    container_name: fastapi
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    depends_on:
      ollama:
        condition: service_healthy  # Wait for Ollama to be ready
    networks:
      - ollama-docker
    environment:
      - OLLAMA_API_URL=http://ollama:11434/  # Use correct API URL
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ./wait-for-it.sh ollama:11434 --timeout=60 --strict -- uvicorn main:app --host 0.0.0.0 --port 8000

networks:
  ollama-docker:
    driver: bridge  # Ensures both containers communicate properly
