version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
      - ./start-ollama.sh:/start-ollama.sh
    container_name: ollama
    restart: always
    networks:
      - ollama-docker
    healthcheck:
      test: [ "CMD", "pgrep", "-f", "ollama" ]
      interval: 30s
      retries: 10
      start_period: 120s
      timeout: 10s
    entrypoint: /bin/sh
    command: /start-ollama.sh
    
  fastapi:
    build:
      context: .              # Set build context to the repository root
      dockerfile: api/Dockerfile  # Specify the Dockerfile location relative to the context
    container_name: fastapi
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    depends_on:
      - ollama  # Ensure Ollama is running before starting FastAPI
      
networks:
  ollama-docker:
    external: false

